# Generated by Django 5.2 on 2025-09-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0028_alter_exceldatabase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelView',
            fields=[
            ],
            options={
                'verbose_name': '엑셀 뷰',
                'verbose_name_plural': '엑셀 뷰',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='OptionA',
            fields=[
            ],
            options={
                'verbose_name': 'Option A',
                'verbose_name_plural': 'Option A',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='OptionB',
            fields=[
            ],
            options={
                'verbose_name': 'Option B',
                'verbose_name_plural': 'Option B',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
    ]
