# Generated by Django 5.2 on 2025-09-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiona',
            options={'verbose_name': 'Order ID List', 'verbose_name_plural': 'Order ID List'},
        ),
        migrations.AlterModelOptions(
            name='optionb',
            options={'verbose_name': 'Request ID List', 'verbose_name_plural': 'Request ID List'},
        ),
    ]
