# Generated by Django 5.2 on 2025-11-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_optiona_options_alter_optionb_options'),
        ('requests', '0034_alter_request_final_option_alter_request_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelView',
        ),
        migrations.DeleteModel(
            name='OptionA',
        ),
        migrations.DeleteModel(
            name='OptionB',
        ),
        migrations.CreateModel(
            name='IntegratedView',
            fields=[
            ],
            options={
                'verbose_name': '1. 통합 관리',
                'verbose_name_plural': '1. 통합 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
            ],
            options={
                'verbose_name': '2. 주문서 관리 (추가/삭제, 결제 처리)',
                'verbose_name_plural': '2. 주문서 관리 (추가/삭제, 결제 처리)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='RequestManagement',
            fields=[
            ],
            options={
                'verbose_name': '3. 요청서 관리 (파일/작업)',
                'verbose_name_plural': '3. 요청서 관리 (파일/작업)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
    ]
