# Generated by Django 5.2 on 2025-04-15 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, verbose_name='타입')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
            ],
            options={
                'verbose_name': '템플릿',
                'verbose_name_plural': '템플릿 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': '신청서', 'verbose_name_plural': '신청서 목록'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='request',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='동의 여부'),
        ),
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, max_length=3072, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'mp4', 'avi', 'mov'])], verbose_name='첨부파일'),
        ),
        migrations.AddField(
            model_name='request',
            name='draft_format',
            field=models.CharField(blank=True, choices=[('hwp', 'HWP'), ('txt', 'TXT'), ('docx', 'DOCX')], max_length=10, null=True, verbose_name='초안 형식'),
        ),
        migrations.AddField(
            model_name='request',
            name='final_option',
            field=models.CharField(blank=True, choices=[('file', '파일'), ('file_usb', '파일+우편'), ('file_usb_post', '파일+우편+USB')], max_length=20, null=True, verbose_name='최종본 옵션'),
        ),
        migrations.AddField(
            model_name='request',
            name='recording_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='녹음일시'),
        ),
        migrations.AddField(
            model_name='request',
            name='recording_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='녹음장소'),
        ),
        migrations.AddField(
            model_name='request',
            name='speaker_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='화자 수'),
        ),
        migrations.AddField(
            model_name='request',
            name='speaker_info',
            field=models.TextField(blank=True, null=True, verbose_name='화자 정보'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='신청자명'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='대상자명')),
                ('contact', models.CharField(max_length=100, verbose_name='연락처/이메일')),
                ('send_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, verbose_name='전송 수단')),
                ('is_success', models.BooleanField(default=False, verbose_name='전송 성공 여부')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 시간')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.template', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '발송 로그',
                'verbose_name_plural': '발송 로그 목록',
            },
        ),
        migrations.DeleteModel(
            name='RequestFile',
        ),
    ]
