# Generated by Django 5.2 on 2025-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_template_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료됨')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
    ]
