# Generated by Django 5.2 on 2025-04-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendlog_set', to='requests.request', verbose_name='신청서'),
        ),
    ]
