# Generated by Django 5.2 on 2025-04-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_sendlog_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '신청서', 'verbose_name_plural': '신청서 목록'},
        ),
        migrations.AlterModelOptions(
            name='sendlog',
            options={'ordering': ['-sent_at'], 'verbose_name': '발송 내역', 'verbose_name_plural': '발송 내역 목록'},
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='send_method',
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='template',
        ),
        migrations.AddField(
            model_name='sendlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='에러 메시지'),
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='발송 성공 여부'),
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발송 일시'),
        ),
    ]
