# Generated by Django 5.2 on 2025-04-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_options_alter_sendlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, help_text='화자별 특징, 상황 설명, 기재했으면 하는 내용 등을 입력해주세요.', null=True, verbose_name='세부 의뢰 내용'),
        ),
        migrations.AddField(
            model_name='request',
            name='has_additional_info',
            field=models.BooleanField(default=False, verbose_name='세부 의뢰 내용 포함'),
        ),
    ]
