# Generated by Django 5.2 on 2025-04-16 02:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_request_additional_info_request_has_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '요청서', 'verbose_name_plural': '요청서들'},
        ),
        migrations.AlterModelOptions(
            name='sendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '발송 로그', 'verbose_name_plural': '발송 로그들'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='is_success',
        ),
        migrations.RemoveField(
            model_name='sendlog',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='request',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'mp4', 'avi', 'mov'])], verbose_name='오디오 파일'),
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='', verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='새 요청', max_length=255, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='추가 정보'),
        ),
        migrations.AlterField(
            model_name='request',
            name='has_additional_info',
            field=models.BooleanField(default=False, verbose_name='추가 정보 여부'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='에러 메시지'),
        ),
    ]
