# Generated by Django 5.2 on 2025-04-16 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_request_options_alter_sendlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='request',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='request',
            name='draft_format',
        ),
        migrations.RemoveField(
            model_name='request',
            name='final_option',
        ),
        migrations.RemoveField(
            model_name='request',
            name='has_additional_info',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recording_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recording_location',
        ),
        migrations.RemoveField(
            model_name='request',
            name='speaker_count',
        ),
        migrations.RemoveField(
            model_name='request',
            name='speaker_info',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'mp4', 'avi', 'mov'])], verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
    ]
