# Generated by Django 5.2 on 2025-04-16 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_remove_request_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '신청서', 'verbose_name_plural': '신청서'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.AddField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='추가 정보'),
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='request',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='이용약관 동의'),
        ),
        migrations.AddField(
            model_name='request',
            name='draft_format',
            field=models.CharField(choices=[('full', '전체'), ('partial', '부분')], default='full', max_length=20, verbose_name='원고 형식'),
        ),
        migrations.AddField(
            model_name='request',
            name='final_option',
            field=models.CharField(choices=[('basic', '기본'), ('premium', '프리미엄')], default='basic', max_length=20, verbose_name='최종 옵션'),
        ),
        migrations.AddField(
            model_name='request',
            name='has_additional_info',
            field=models.BooleanField(default=False, verbose_name='추가 정보 있음'),
        ),
        migrations.AddField(
            model_name='request',
            name='recording_date',
            field=models.DateField(blank=True, null=True, verbose_name='녹음 날짜'),
        ),
        migrations.AddField(
            model_name='request',
            name='recording_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='녹음 장소'),
        ),
        migrations.AddField(
            model_name='request',
            name='speaker_count',
            field=models.PositiveIntegerField(default=1, verbose_name='화자 수'),
        ),
        migrations.AddField(
            model_name='request',
            name='speaker_info',
            field=models.TextField(blank=True, verbose_name='화자 정보'),
        ),
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requests/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])], verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
