# Generated by Django 5.2 on 2025-04-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_request_options_remove_request_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='draft_format',
            field=models.CharField(choices=[('full', '초안 전체'), ('partial', '초안 부분')], default='full', max_length=20, verbose_name='원고 형식'),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_option',
            field=models.CharField(choices=[('basic', '기본 (1회 교정)'), ('premium', '프리미엄 (2회 교정)')], default='basic', max_length=20, verbose_name='최종 옵션'),
        ),
    ]
