# Generated by Django 5.2 on 2025-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_request_draft_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='draft_format',
            field=models.CharField(choices=[('full', '전체 녹취'), ('partial', '부분 녹취')], default='full', max_length=20, verbose_name='원고 형식'),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_option',
            field=models.CharField(choices=[('file', '파일'), ('file_usb', '파일+우편'), ('file_usb_post', '파일+우편+USB')], default='file', max_length=20, verbose_name='최종 옵션'),
        ),
    ]
