# Generated by Django 5.2 on 2025-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_alter_request_draft_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='draft_format',
            field=models.CharField(choices=[('hwp', 'hwp'), ('txt', 'txt'), ('docx', 'docx')], default='full', max_length=20, verbose_name='원고 형식'),
        ),
    ]
