# Generated by Django 5.2 on 2025-04-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_alter_request_draft_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='이용약관 동의'),
        ),
        migrations.AlterField(
            model_name='request',
            name='draft_format',
            field=models.CharField(choices=[('hwp', 'hwp'), ('txt', 'txt'), ('docx', 'docx')], default='hwp', max_length=20, verbose_name='원고 형식'),
        ),
    ]
