# Generated by Django 5.2 on 2025-04-16 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_alter_request_agreement_alter_request_draft_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='has_additional_info',
        ),
        migrations.AddField(
            model_name='request',
            name='has_additional',
            field=models.BooleanField(default=False, verbose_name='추가 정보'),
        ),
        migrations.AlterField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='세부 의뢰 내용'),
        ),
        migrations.AlterField(
            model_name='request',
            name='recording_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='녹음 일시'),
        ),
        migrations.AlterField(
            model_name='request',
            name='recording_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='녹음 장소'),
        ),
        migrations.AlterField(
            model_name='request',
            name='speaker_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='화자 수'),
        ),
    ]
