# Generated by Django 5.2 on 2025-04-16 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_remove_request_has_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='request',
            name='has_additional',
        ),
        migrations.AddField(
            model_name='request',
            name='detail_info',
            field=models.TextField(blank=True, verbose_name='세부 내용 정보'),
        ),
        migrations.AddField(
            model_name='request',
            name='has_detail',
            field=models.BooleanField(default=False, verbose_name='세부 내용'),
        ),
        migrations.AlterField(
            model_name='request',
            name='speaker_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='화자 수'),
        ),
    ]
