# Generated by Django 5.2 on 2025-05-23 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_remove_request_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '요청서', 'verbose_name_plural': '요청서들'},
        ),
        migrations.AlterField(
            model_name='request',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='동의'),
        ),
        migrations.AlterField(
            model_name='request',
            name='speaker_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='화자 수는 최소 1명 이상이어야 합니다.'), django.core.validators.MaxValueValidator(5, message='화자 수는 최대 5명까지 가능합니다.')], verbose_name='화자 수'),
        ),
        migrations.AlterField(
            model_name='request',
            name='speaker_info',
            field=models.JSONField(blank=True, default=list, verbose_name='화자 정보'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/files/%Y/%m/%d/', verbose_name='첨부파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requests.request', verbose_name='요청서')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일들',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
