# Generated by Django 5.2 on 2025-05-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_alter_request_options_alter_request_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='attachment',
        ),
    ]
