# Generated by Django 5.2 on 2025-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_remove_request_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='원본 파일명'),
        ),
    ]
