# Generated by Django 5.2 on 2025-05-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_file_original_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '첨부파일', 'verbose_name_plural': '첨부 파일'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': '요청서', 'verbose_name_plural': '요청서'},
        ),
        migrations.AlterModelOptions(
            name='sendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '발송 로그', 'verbose_name_plural': '발송 로그'},
        ),
    ]
