# Generated by Django 5.2 on 2025-05-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_alter_file_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255, unique=True, verbose_name='S3 파일 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_files', to='requests.request', verbose_name='요청서')),
            ],
            options={
                'verbose_name': '요청 파일',
                'verbose_name_plural': '요청 파일 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255, unique=True, verbose_name='S3 파일 키')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(verbose_name='업로드 일시')),
                ('is_registered', models.BooleanField(default=False, verbose_name='등록 여부')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3_files', to='requests.request', verbose_name='요청서')),
            ],
            options={
                'verbose_name': 'S3 파일',
                'verbose_name_plural': 'S3 파일 목록',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
