# Generated by Django 5.2 on 2025-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_requestfile_s3file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_temporary',
            field=models.BooleanField(default=True, verbose_name='임시 신청서 여부'),
        ),
    ]
