# Generated by Django 5.2 on 2025-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_request_is_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3file',
            name='request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_temporary',
        ),
        migrations.DeleteModel(
            name='RequestFile',
        ),
        migrations.DeleteModel(
            name='S3File',
        ),
    ]
