# Generated by Django 5.2 on 2025-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_remove_s3file_request_remove_request_is_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_temporary',
            field=models.BooleanField(default=True, verbose_name='임시 신청서 여부'),
        ),
    ]
