# Generated by Django 5.2 on 2025-06-11 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_request_is_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': '첨부파일', 'verbose_name_plural': '첨부 파일'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
