# Generated by Django 5.2 on 2025-09-20 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_alter_file_options_remove_file_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDatabase',
            fields=[
            ],
            options={
                'verbose_name': '엑셀 데이터베이스',
                'verbose_name_plural': '엑셀 데이터베이스',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.AddField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='상세 정보'),
        ),
        migrations.AddField(
            model_name='request',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='취소 사유'),
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='예상 견적'),
        ),
        migrations.AddField(
            model_name='request',
            name='impossible_reason',
            field=models.TextField(blank=True, verbose_name='작업불가 사유'),
        ),
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, verbose_name='기타 정보'),
        ),
        migrations.AddField(
            model_name='request',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='request',
            name='partial_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='부분 녹취 구간'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='결제 금액'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='결제 여부'),
        ),
        migrations.AddField(
            model_name='request',
            name='price_change_reason',
            field=models.TextField(blank=True, verbose_name='결제금액 변동 사유'),
        ),
        migrations.AddField(
            model_name='request',
            name='recording_type',
            field=models.CharField(default='전체', max_length=20, verbose_name='녹취 타입'),
        ),
        migrations.AddField(
            model_name='request',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='환불 금액'),
        ),
        migrations.AddField(
            model_name='request',
            name='speaker_names',
            field=models.TextField(blank=True, verbose_name='화자 이름'),
        ),
        migrations.AddField(
            model_name='request',
            name='total_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='총 길이'),
        ),
        migrations.AddField(
            model_name='request',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='속기록'),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_option',
            field=models.CharField(choices=[('file', '파일'), ('file_usb', '파일+우편'), ('file_usb_cd', '파일+우편+CD'), ('file_usb_post', '파일+우편+USB')], default='file', max_length=20, verbose_name='최종 옵션'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('received', '접수됨'), ('payment_completed', '결제완료'), ('in_progress', '작업중'), ('work_completed', '작업완료'), ('sent', '발송완료'), ('impossible', '작업불가'), ('cancelled', '취소됨'), ('refunded', '환불완료')], default='received', max_length=20, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='상태 변경 사유')),
                ('notification_sent', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='requests.request')),
            ],
            options={
                'verbose_name': '상태 변경 이력',
                'verbose_name_plural': '상태 변경 이력',
                'ordering': ['-changed_at'],
            },
        ),
    ]
