# Generated by Django 5.2 on 2025-09-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0025_exceldatabase_request_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Request ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order ID'),
        ),
    ]
