# Generated by Django 5.2 on 2025-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0026_request_request_id_alter_request_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Order ID'),
        ),
    ]
