# Generated by Django 5.2 on 2025-09-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_alter_request_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceldatabase',
            options={'verbose_name': '엑셀 데이터베이스', 'verbose_name_plural': '엑셀 뷰'},
        ),
    ]
