# Generated by Django 5.2 on 2025-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0028_alter_exceldatabase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order_status',
            field=models.CharField(choices=[('received', '접수됨'), ('payment_completed', '결제완료'), ('sent', '발송완료'), ('impossible', '작업불가'), ('cancelled', '취소됨'), ('refunded', '환불완료')], default='received', help_text='주문 전체 상태', max_length=20, verbose_name='Order 상태'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('received', '접수됨'), ('in_progress', '작업중'), ('work_completed', '작업완료'), ('sent', '발송완료'), ('impossible', '작업불가'), ('cancelled', '취소됨')], default='received', help_text='개별 파일 작업 상태', max_length=20, verbose_name='Request 상태'),
        ),
    ]
