# Generated by Django 5.2 on 2025-09-28 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0029_request_order_status_alter_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='transcript',
        ),
        migrations.AddField(
            model_name='request',
            name='transcript_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_requests', to='requests.file', verbose_name='속기록 파일'),
        ),
    ]
