# Generated by Django 5.2 on 2025-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0030_remove_request_transcript_request_transcript_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='email_type',
            field=models.CharField(blank=True, choices=[('service_completion', '서비스 신청 완료 안내'), ('quotation_guide', '견적 및 입금 안내'), ('payment_completion_guide', '결제 완료 안내'), ('draft_guide', '속기록 초안/수정안 발송'), ('final_draft_guide', '속기록 최종안 발송')], max_length=50, null=True, verbose_name='이메일 종류'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='order_id',
            field=models.CharField(blank=True, help_text='발송 시점의 Order ID', max_length=10, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='발송 시점의 결제 금액', max_digits=10, null=True, verbose_name='안내 금액'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='수신자 이메일'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='발송 성공 여부'),
        ),
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['order_id', 'email_type', '-created_at'], name='requests_se_order_i_92b3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['recipient_email', 'email_type', '-created_at'], name='requests_se_recipie_8b1996_idx'),
        ),
    ]
