# Generated by Django 5.2 on 2025-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0031_sendlog_email_type_sendlog_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='sent_request_id',
            field=models.CharField(blank=True, help_text='발송 시점의 Request ID (초안/최종안용)', max_length=50, null=True, verbose_name='Request ID'),
        ),
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['sent_request_id', 'email_type', '-created_at'], name='requests_se_sent_re_28869e_idx'),
        ),
    ]
