# Generated by Django 5.2 on 2025-10-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0032_sendlog_sent_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requests.request', verbose_name='요청서'),
        ),
    ]
