# Generated by Django 5.2 on 2025-11-02 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0033_alter_file_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='final_option',
            field=models.CharField(choices=[('file', '파일'), ('file_usb', '파일 + 등기 우편 (+5,000원)'), ('file_usb_cd', '파일 + 등기 우편 + CD (+6,000원)'), ('file_usb_post', '파일 + 등기 우편 + USB (+10,000원)')], default='file', max_length=20, verbose_name='최종 옵션'),
        ),
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, verbose_name='상세 정보'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='결제 금액은 0 이상이어야 합니다.')], verbose_name='결제 금액'),
        ),
        migrations.AlterField(
            model_name='request',
            name='recording_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='녹음 종류'),
        ),
        migrations.AlterField(
            model_name='request',
            name='speaker_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='화자 수는 최소 1명 이상이어야 합니다.'), django.core.validators.MaxValueValidator(10, message='화자 수는 최대 10명까지 가능합니다.')], verbose_name='화자 수'),
        ),
    ]
