# Generated by Django 5.2 on 2025-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0034_alter_request_final_option_alter_request_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Order ID'),
        ),
    ]
