# Generated by Django 5.2 on 2025-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0035_alter_request_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlog',
            name='order_id',
            field=models.CharField(blank=True, help_text='발송 시점의 Order ID', max_length=20, null=True, verbose_name='Order ID'),
        ),
    ]
